### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by HiranChaudhuri** [elico/yt-classification-service-example#1]
Thank you for having a nice example how to wrap redwood into a container.
While trying it out I always seem to have problems with ssl-bump. I see error messages like

```
2021-02-27 21:13:12.939597,192.168.178.68,www.google.com,www.google.com:443,error in handshake with client: EOF,cached certificate,aa7744226c695c0b2e440419848cf700
2021-02-27 21:13:14.106482,192.168.178.68,vaadin.com,vaadin.com:443,error in handshake with client: remote error: tls: unknown certificate,,aa7744226c695c0b2e440419848cf700
```

in the logfile and see messages like this one in the browser:

![Screenshot from 2021-02-27 22-41-59](https://user-images.githubusercontent.com/6866487/109401131-29766600-794d-11eb-943d-effc7a77c697.png)

And this although I already added ca-certificates to https://github.com/elico/yt-classification-service-example/blob/a6c2f1733d9cd73cb8d15778cb8f55c743bee799/redwood/Dockerfile#L18

So I am not sure: Does this error still relate to a broken truststore, or may it point to some problem in redwood?

**Comment by HiranChaudhuri** [comment]
Oh, btw when trying to access the same URLs from within the docker container using curl it works as expected: the content gets downloaded, so I assume the container's trust store is ok.

**Comment by elico** [comment]
> Oh, btw when trying to access the same URLs from within the docker container using curl it works as expected: the content gets downloaded, so I assume the container's trust store is ok.

This issue is specific for Firefox.
You can try in another browser to see how it works there.

Do you understand how ssl bump works?
You need to create a root ca key and to save it across restarts of the instance.
Also you will need to install the root ca public key on the browser.

Let me know if you are missing something.

**Comment by HiranChaudhuri** [comment]
Thank you for your response. Meanwhile I learned more:
The TLS certificate I was using was intended to resemble an intermediate CA - however the certificate did not contain the CA purpose. So actually it was a leaf certificate that redwood tried to use for signing more. It seems redwood did not complain, while Firefox did. It only occurred to me when I tried to import this buggy CA certificate explicitly into Firefox (despite the fact that the root CA was already imported).

So now I am using a self-signed CA certificate and it works much better. Will try to go for an intermediate again but with much better validation of the certificates.

But I guess having the ca-certificates in the redwood container at runtime is still required for ssl-bump, or am I wrong here?

**Comment by elico** [comment]
@HiranChaudhuri Have a CA certificate either top level or intimidate should be preset in the docker.
you can mount a single file as a volume to monut the key and cert file.

**Comment by hiranchaudhuri1** [comment]
I still have the feeling we are talking about two different things.

Yes, I first used single file mounts to provide cert and key, meanwhile I prefer to mount the whole /etc/redwood directory from outside to be more flexible on the configuration.

What I am talking about is the ssl-bump. It works like redwood acts as 'real' proxy for SSL connections. Which means it establishes an SSL connection, performs the request, ensures it has a fake certificate for that site and presents both certificate and response to the client. How would redwood validate the certificates of the remote sites? (I hope it does???)

**Comment by elico** [comment]
@HiranChaudhuri using the Linux OS certificates store.
In this specific case it `alpine`.
If you are familiar with how `curl` or `wget` are validating the certificate it uses the same store.
If you want to use your own certificates store you can mount one.
I would start by copying the default `alpine` and move on from there.

**Comment by hiranchaudhuri1** [comment]
Yes, now we are getting closer. :-)

Up there I indicated that the container you created is based on alpine but has no certificates installed. I noticed this when running curl from within the container to debug connectivity. My solution to the missing root certificates was to add the package ca-certificates to the container.

Mind the fact that it may seem added - but only on the container used to compile redwood - not the one that would be running it.

**Comment by elico** [comment]
@hiranchaudhuri1 I fixed this in:
https://github.com/elico/yt-classification-service-example/commit/2323858999b034a55ab5f8b2ffab061075d96a29

I don't know how I missed it.
On my tests it worked in the major sites.

Something that you might want to look at is:
https://github.com/elico/windows-rootca-autodeploy-create

I have a newer version of this code but yet to upload it,

**Comment by hiranchaudhuri1** [comment]
That commit nailed it. Well, if your tests on major sites worked it is easy to miss. (y)
With that not only the initial gist but also the side effect is resolved and we can close the issue.

For your other code: What is the gist of it? Would it be a certificate authority, or is it more code to deploy certificates into the Windows truststore? In my setup I use Hashicorp Vault and solely Ubuntu desktop machines...
